name: 'bike_dbt_project'
version: '1.0'
config-version: 2

profile: bike_dbt_project  

source-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  bike_dbt_project:
    staging:
      materialized: view
    marts:
      materialized: table
